#!/bin/bash

MOM_CLI_IMPL="net.echinopsii.ariane.community.messaging.rabbitmq.Client"
MOM_CLI_RBQ_PRODUCT="TradeworkflowDemo.FrontOfficeService"
MOM_CLI_RBQ_INFORMATION=${FO_SERVICE_NAME:-"FrontOfficeService"}
MOM_CLI_RBQ_COPYRIGHT="AGPLv3"
MOM_CLI_RBQ_VERSION="0.3.0-SNAPSHOT"
MOM_HOST_FQDN=${MOM_HOST}
MOM_HOST_PORT=${MOM_PORT:-"5672"}
CONTAINER_IP=`ifconfig | grep "inet" | grep "broadcast" | awk '{print $2}'`
ARIANE_PGURL=${A_PGURL:-"jmx://${CONTAINER_IP}:9069"}
ARIANE_OSI=${A_OSI}
ARIANE_OTM=${A_OTM}
ARIANE_APP=${A_APP:-"FrontOfficeService"}
ARIANE_CMP=${A_CMP:-"echinopsii"}
FO_FD_BASE_TOPIC=${FO_FD_BTOPIC:-"PRICE"}
FO_MO_QUEUE=${FO_MO_Q:-"MOQ"}
FO_STOCKS_BLOCK_SIZE=${FO_SBS:-"30"}
FO_STOCKS_SOLD_MINDIF=${FO_SSM:-"30"}

if [ "${MOM_HOST_FQDN}" == "" ]; then
    echo "Target RabbitMQ FQDN is not defined !"
    return -1
fi

if [ ! -f /opt/ariane/tradeworkflow/distrib/conf/frontoffice.properties.ini ]; then
    cp /opt/ariane/tradeworkflow/distrib/conf/frontoffice.properties /opt/ariane/tradeworkflow/distrib/conf/frontoffice.properties.ini
fi

cp /opt/ariane/tradeworkflow/distrib/conf/frontoffice.properties.ini /opt/ariane/tradeworkflow/distrib/conf/frontoffice.properties

sed -i "s/##mom_cli.impl/${MOM_CLI_IMPL}/g" /opt/ariane/tradeworkflow/distrib/conf/frontoffice.properties
sed -i "s/##mom_cli.rabbitmq.product/${MOM_CLI_RBQ_PRODUCT}/g" /opt/ariane/tradeworkflow/distrib/conf/frontoffice.properties
sed -i "s/##mom_cli.rabbitmq.information/${MOM_CLI_RBQ_INFORMATION}/g" /opt/ariane/tradeworkflow/distrib/conf/frontoffice.properties
sed -i "s/##mom_cli.rabbitmq.copyright/${MOM_CLI_RBQ_COPYRIGHT}/g" /opt/ariane/tradeworkflow/distrib/conf/frontoffice.properties
sed -i "s/##mom_cli.rabbitmq.version/${MOM_CLI_RBQ_VERSION}/g" /opt/ariane/tradeworkflow/distrib/conf/frontoffice.properties
sed -i "s/##mom_host.fqdn/${MOM_HOST_FQDN}/g" /opt/ariane/tradeworkflow/distrib/conf/frontoffice.properties
sed -i "s/##mom_host.port/${MOM_HOST_PORT}/g" /opt/ariane/tradeworkflow/distrib/conf/frontoffice.properties
sed -i "s@##ariane.pgurl@${ARIANE_PGURL}@g" /opt/ariane/tradeworkflow/distrib/conf/frontoffice.properties
sed -i "s/##ariane.osi/${ARIANE_OSI}/g" /opt/ariane/tradeworkflow/distrib/conf/frontoffice.properties
sed -i "s/##ariane.otm/${ARIANE_OTM}/g" /opt/ariane/tradeworkflow/distrib/conf/frontoffice.properties
sed -i "s/##ariane.app/${ARIANE_APP}/g" /opt/ariane/tradeworkflow/distrib/conf/frontoffice.properties
sed -i "s/##ariane.cmp/${ARIANE_CMP}/g" /opt/ariane/tradeworkflow/distrib/conf/frontoffice.properties
sed -i "s/##front_office.feeder_base_topic/${FO_FD_BASE_TOPIC}/g" /opt/ariane/tradeworkflow/distrib/conf/frontoffice.properties
sed -i "s/##front_office.mo_queue/${FO_MO_QUEUE}/g" /opt/ariane/tradeworkflow/distrib/conf/frontoffice.properties
sed -i "s/##front_office.stocks_block_size/${FO_STOCKS_BLOCK_SIZE}/g" /opt/ariane/tradeworkflow/distrib/conf/frontoffice.properties
sed -i "s/##front_office.stocks_sold_mindif/${FO_STOCKS_SOLD_MINDIF}/g" /opt/ariane/tradeworkflow/distrib/conf/frontoffice.properties

export JAVA_HOME=/opt/java/jdk1.7.0_75/
export PATH=$JAVA_HOME/bin:$PATH

/opt/ariane/tradeworkflow/distrib/bin/frontoffice.sh
