version: "2"

services:
  n1:
    image: echinopsii/cassandra:cluster.2.2
    networks:
      - cass_clu
    environment:
      - CASSANDRA_TOKEN=-9223372036854775808
      - CASSANDRA_CLUSTERNAME=echinopsii
      - CASSANDRA_BROADCAST_ADDRESS
    ports:
      - 17000:7000
      - 17001:7001
      - 17199:7199
      - 19042:9042
      - 19160:9160

  n2:
    image: echinopsii/cassandra:cluster.2.2
    networks:
      - cass_clu
    environment:
      - CASSANDRA_TOKEN=-3074457345618258603
      - CASSANDRA_CLUSTERNAME=echinopsii
      - CASSANDRA_SEEDS
      - CASSANDRA_BROADCAST_ADDRESS
    ports:
      - 27000:7000
      - 27001:7001
      - 27199:7199
      - 29042:9042
      - 29160:9160

  n3:
    image: echinopsii/cassandra:cluster.2.2
    networks:
      - cass_clu
    environment:
      - CASSANDRA_TOKEN=3074457345618258602
      - CASSANDRA_CLUSTERNAME=echinopsii
      - CASSANDRA_SEEDS
      - CASSANDRA_BROADCAST_ADDRESS
    ports:
      - 37000:7000
      - 37001:7001
      - 37199:7199
      - 39042:9042
      - 39160:9160

networks:
  cass_clu:
    driver: bridge
    driver_opts:
       com.docker.network.bridge.name: "cass_cluster"
